# Site settings
title: Damian Zermeno
description: Damian Zermeno's Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Damian Zermeno
user_description: With 10+ years of sysadmin experience, I am an innovative IT professional known for my passion for open source and automation. I thrive on simplifying complex tasks, driving continuous improvement, and delivering efficient solutions.  Let's make a difference together.

user_title: DevOps/SRE Engineer
email: damian.zermeno.s@gmail.com
twitter_username: aztoatl
linkedin_username: damian-zermeño-valadez
github_username:  aztoatl
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
role: Driving digital transformation with over a decade of expertise in server management and process automation, I have a proven track record in deploying DevOps methodologies to streamline operations and ensure the high availability of services across complex environments.
skills: Focusing on the core of DevOps, I excel in integrating continuous integration (CI) and continuous delivery (CD) systems, leveraging Jenkins, Ansible, and Docker to promote agile development practices and infrastructure as code (IaC), ensuring rapid, reliable, and repeatable deployments.
tools: Adept in an extensive array of DevOps tools and technologies, my expertise spans Python scripting, Linux system administration, and the orchestration of containerized applications with Docker and Kubernetes. Proficient in automating deployment pipelines using Ansible and managing infrastructure with Terraform, I enhance operational efficiencies and foster collaboration across development teams.
exclude: ['package.json', 'src', 'node_modules', 'vendor']

